# POD Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  labels:
    app: maven-web-application
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: maven-web-application
  template:
    metadata:
     name: javawebapppod
     labels:
       app: maven-web-application
    spec:
      containers:
      - name: javawebappcontainer
        image: karthikdocker123/maven-web-application
        ports:
        - containerPort: 8080
---

---
# Service Manifest
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
...


